# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseUrl= https://localhost:7291



####
GET {{baseUrl}}/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc5OTAwMDk0LCJleHAiOjE3Nzk5MDM2OTQsImlhdCI6MTc3OTkwMDA5NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gm-BrOEetVlayqe2Ei3Z6rNkPSqTeIDkdbXQRdDpzHA




####
GET {{baseUrl}}/api/customers/ec34c9fe-e321-4e12-baa2-7d9c7a04a0ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc5OTAwMDk0LCJleHAiOjE3Nzk5MDM2OTQsImlhdCI6MTc3OTkwMDA5NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gm-BrOEetVlayqe2Ei3Z6rNkPSqTeIDkdbXQRdDpzHA

######

POST {{baseUrl}}/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc5OTAwMDk0LCJleHAiOjE3Nzk5MDM2OTQsImlhdCI6MTc3OTkwMDA5NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gm-BrOEetVlayqe2Ei3Z6rNkPSqTeIDkdbXQRdDpzHA
Content-Type: application/json

{
  "name": "ali3",
  "email": "lool4@gmail.com",
  "phoneNumber": "4919923690",
  "vehicles": [
    {
      "make": "Toyota",
      "model": "Camry",
      "year": 2020,
      "licensePlate": "ABC1423"
    },
    {
      "make": "BMW",
      "model": "X5",
      "year": 2022,
      "licensePlate": "XY6Z999"
    }
  ]
}
######


PUT {{baseUrl}}/api/customers/ec34c9fe-e321-4e12-baa2-7d9c7a04a0ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc5OTAwMDk0LCJleHAiOjE3Nzk5MDM2OTQsImlhdCI6MTc3OTkwMDA5NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gm-BrOEetVlayqe2Ei3Z6rNkPSqTeIDkdbXQRdDpzHA
Content-Type: application/json

{
   "name":"alimohammed",
   "email":"ali@gmail.com",
   "phoneNumber":"5999988775",
   "vehicles": [
    {
      "vehicleId": "0fbe8c6f-61e8-429f-97b3-4185dfee04a2",
      "make": "Toyota",
      "model": "Camry",
      "year": 2020,
      "licensePlate": "ABC123"
    }]


}

###
 
DELETE {{baseUrl}}/api/customers/938b8c5b-7bc0-42cd-bd55-4686ee012b81
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc5OTAwMDk0LCJleHAiOjE3Nzk5MDM2OTQsImlhdCI6MTc3OTkwMDA5NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gm-BrOEetVlayqe2Ei3Z6rNkPSqTeIDkdbXQRdDpzHA



######


GET {{baseUrl}}/api/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc5OTAwMDk0LCJleHAiOjE3Nzk5MDM2OTQsImlhdCI6MTc3OTkwMDA5NCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gm-BrOEetVlayqe2Ei3Z6rNkPSqTeIDkdbXQRdDpzHA


POST {{baseUrl}}/api/identity/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "Test123"
}


####
GET {{baseUrl}}/api/identity/current-user/claims
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTgxYzRlNy1hYWMzLTRhYWMtYTQ5ZC02ZTRiMGJjMTM2NzkiLCJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwibmJmIjoxNzc4OTQ0Mjg1LCJleHAiOjE3Nzg5NDc4ODUsImlhdCI6MTc3ODk0NDI4NSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.9wjoRAAF0G3pAvmiqhSGWT2Od42348MRVKuGTOGbQ48







####
POST {{baseUrl}}/api/repairtasks
Content-Type: application/json
{
  "name": "Oil Change",
  "laborCost": 100,
  "estimatedDurationInMins": 30,
  "parts": [
    {
      "name": "Oil Filter",
      "cost": 20,
      "quantity": 1
    },
    {
      "name": "Engine Oil",
      "cost": 50,
      "quantity": 2
    }
  ]
}


####
POST {{baseUrl}}/api/repairtasks
Content-Type: application/json
{
  "name": "Oil Change",
  "laborCost": 100,
  "estimatedDurationInMins": 30,
  "parts": [
    {
      "name": "Oil Bottle",
      "cost": 20,
      "quantity": 1
    }
    
  ]
}

###
DELETE {{baseUrl}}/api/repairtask/3b4d3ced-5976-4a2c-82e9-3579fedcd4e7


###
PUT {{baseUrl}}/api/repairtask/cbf91b79-35a5-40c8-8302-ef9ec31bc3fb
Content-Type: application/json


{
  "name": "Oil Full",
  "estimatedDurationInMins": 30,
  "laborCost": 90,
   "parts": [
    {
      "name": "Oil Bottle",
      "cost": 20,
      "quantity": 1
    }
   ]
}


####
GET {{baseUrl}}/api/repairtask/cbf91b79-35a5-40c8-8302-ef9ec31bc3fb


####
GET {{baseUrl}}/api/repairtasks



####
POST {{baseUrl}}/api/workorders
Content-Type: application/json

{
    "vehicleId":"8434ec38-4e4e-4dbc-8fd9-5dcbe473d1e6",
    "startAtUtc":"2026-05-09T10:00:00Z",
    "repairTaskIds":["0b2c46ba-3fa3-41a6-9806-14d5c214ebb9"
    ],
    "laborId":"a1645873-51bb-4308-8b6d-c204743d6331"
       
    
}

####
DELETE {{baseUrl}}/api/workorders/9d334905-8126-4a0a-beb2-641b03938e92


####
GET {{baseUrl}}/api/workorders/9d334905-8126-4a0a-beb2-641b03938e92h


####
GET {{baseUrl}}/api/labors


###
PUT {{baseUrl}}/api/workorders/c0c6eb0b-389a-476d-bfde-778289026ec7/repairtasks
Content-Type: application/json



   ["b6a13520-1274-4efe-80d0-0fd2c6612a67","de7a2cfc-3f41-4b98-aac3-2f9529597f7b"]




######
PUT {{baseUrl}}/api/workorders/c0c6eb0b-389a-476d-bfde-778289026ec7/labor/a1645873-51bb-4308-8b6d-c204743d6331



####
GET {{baseUrl}}/openapi/v1.json