# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseUrl=https://localhost:7291

POST {{baseUrl}}/api/customers
Content-Type: application/json
{
   "name":"ahmed",
   "email":"abeds@gmail.com",
   "phoneNumber":"055"


}

######

POST {{baseUrl}}/api/customers
Content-Type: application/json
{
   "name":"ali",
   "email":"ali@gmail.com",
   "phoneNumber":"5999988775"


}
######


PUT {{baseUrl}}/api/customers/1fc7292d-a37d-4113-a0c5-2a74c99e2f75
Content-Type: application/json

{
   "name":"alimohammed",
   "email":"ali@gmail.com",
   "phoneNumber":"5999988775"


}

###
 
DELETE {{baseUrl}}/api/customers/79f186c9-0035-4e83-8998-2e9ab46760de


####
POST {{baseUrl}}/api/Auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

###
POST {{baseUrl}}/api/Auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}
######

POST {{baseUrl}}/api/Auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test123"
}
